repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*legacy/.*$
      - id: end-of-file-fixer
        exclude: ^.*legacy/.*$
      - id: check-yaml
        exclude: ^.*legacy/.*$
      - id: check-added-large-files
        exclude: ^.*legacy/.*$
      - id: check-merge-conflict
        exclude: ^.*legacy/.*$
      - id: check-case-conflict
        exclude: ^.*legacy/.*$
      - id: check-ast
        exclude: ^.*legacy/.*$
      - id: check-json
        exclude: ^.*legacy/.*$
      - id: check-merge-conflict
        exclude: ^.*legacy/.*$
      - id: detect-private-key
        exclude: ^.*legacy/.*$

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: [--line-length=100]
        exclude: ^.*legacy/.*$

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=100]
        exclude: ^.*legacy/.*$

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "100"]
        exclude: ^.*legacy/.*$

  - repo: local
    hooks:
      - id: clear-notebook-outputs
        name: Clear Notebook Outputs with nbconvert
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
        language: system
        files: \.ipynb$
        exclude: ^.*legacy/.*$
        stages: [commit]
